CREATE SEQUENCE PASSWORD_RESET_TOKEN_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE PASSWORD_RESET_TOKENS
(
    ID NUMBER(19,0) NOT NULL,
    CREATED_AT TIMESTAMP(6),
    USER_ID NUMBER(19,0) NOT NULL,
    TOKEN_HASH VARCHAR2(64 CHAR) NOT NULL,
    EXPIRES_AT TIMESTAMP(6) NOT NULL,
    USED NUMBER(1,0) DEFAULT 0 NOT NULL,
    USED_AT TIMESTAMP(6),
    CONSTRAINT PK_PASSWORD_RESET_TOKENS PRIMARY KEY (ID),
    CONSTRAINT UK_PASSWORD_RESET_TOKENS_HASH UNIQUE (TOKEN_HASH),
    CONSTRAINT FK_PASSWORD_RESET_TOKENS_USER FOREIGN KEY (USER_ID) REFERENCES USERS (ID),
    CONSTRAINT CK_PASSWORD_RESET_TOKENS_USED CHECK (USED IN (0, 1))
);
