spring.application.name=pixel_Project2

# Oracle ???? ??
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@175.126.145.185:1521:orcl
spring.datasource.username=aibe5team5
spring.datasource.password=akstp

# JPA/Hibernate ?? (??? ?? ??)
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

# Table Creation Option (Must be set to 'create')
spring.jpa.hibernate.ddl-auto=create

# Can check SQL in console while operating (Only Debug)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true