CREATE SEQUENCE MESSAGE_REVIEW_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE MESSAGE_REVIEWS (
    REVIEW_ID NUMBER(19) PRIMARY KEY,
    CONVERSATION_ID NUMBER(19) NOT NULL,
    REVIEWER_ID NUMBER(19) NOT NULL,
    REVIEWEE_ID NUMBER(19) NOT NULL,
    PROJECT_TITLE VARCHAR2(200) NOT NULL,
    RATING NUMBER(1) NOT NULL,
    CONTENT CLOB NOT NULL,
    WORK_CATEGORIES_JSON CLOB,
    COMPLIMENT_TAGS_JSON CLOB,
    CREATED_MESSAGE_REVIEW TIMESTAMP NOT NULL,
    CONSTRAINT UK_MESSAGE_REVIEW_CONVERSATION_REVIEWER UNIQUE (CONVERSATION_ID, REVIEWER_ID),
    CONSTRAINT FK_MESSAGE_REVIEW_CONVERSATION FOREIGN KEY (CONVERSATION_ID) REFERENCES MESSAGE_CONVERSATIONS (CONVERSATION_ID) ON DELETE CASCADE,
    CONSTRAINT FK_MESSAGE_REVIEW_REVIEWER FOREIGN KEY (REVIEWER_ID) REFERENCES USERS (ID),
    CONSTRAINT FK_MESSAGE_REVIEW_REVIEWEE FOREIGN KEY (REVIEWEE_ID) REFERENCES USERS (ID),
    CONSTRAINT CK_MESSAGE_REVIEW_RATING CHECK (RATING BETWEEN 1 AND 5),
    CONSTRAINT CK_MESSAGE_REVIEW_USERS CHECK (REVIEWER_ID <> REVIEWEE_ID)
);

CREATE INDEX IDX_MESSAGE_REVIEWS_REVIEWEE_TIME ON MESSAGE_REVIEWS (REVIEWEE_ID, CREATED_MESSAGE_REVIEW);
