CREATE SEQUENCE MESSAGE_CONVERSATION_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE CHAT_MESSAGE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE MESSAGE_REACTION_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE MESSAGE_PROCESS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE MESSAGE_PROCESS_TASK_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE MESSAGE_CONVERSATIONS (
    CONVERSATION_ID NUMBER(19) PRIMARY KEY,
    USER_ONE_ID NUMBER(19) NOT NULL,
    USER_TWO_ID NUMBER(19) NOT NULL,
    LAST_MESSAGE_AT TIMESTAMP,
    LAST_MESSAGE_PREVIEW VARCHAR2(500),
    USER_ONE_LAST_READ_MESSAGE_ID NUMBER(19),
    USER_TWO_LAST_READ_MESSAGE_ID NUMBER(19),
    CREATED_MESSAGE_CONVERSATION TIMESTAMP NOT NULL,
    CONSTRAINT UK_MSG_CONV_USERS UNIQUE (USER_ONE_ID, USER_TWO_ID),
    CONSTRAINT CK_MSG_CONV_USERS CHECK (USER_ONE_ID <> USER_TWO_ID),
    CONSTRAINT FK_MSG_CONV_U1 FOREIGN KEY (USER_ONE_ID) REFERENCES USERS (ID),
    CONSTRAINT FK_MSG_CONV_U2 FOREIGN KEY (USER_TWO_ID) REFERENCES USERS (ID)
);

CREATE TABLE CHAT_MESSAGES (
    MESSAGE_ID NUMBER(19) PRIMARY KEY,
    CONVERSATION_ID NUMBER(19) NOT NULL,
    SENDER_ID NUMBER(19) NOT NULL,
    CLIENT_ID VARCHAR2(100),
    MESSAGE CLOB,
    ATTACHMENTS_JSON CLOB,
    CREATED_MESSAGE TIMESTAMP NOT NULL,
    CONSTRAINT FK_CHAT_MSG_CONV FOREIGN KEY (CONVERSATION_ID) REFERENCES MESSAGE_CONVERSATIONS (CONVERSATION_ID),
    CONSTRAINT FK_CHAT_MSG_USER FOREIGN KEY (SENDER_ID) REFERENCES USERS (ID)
);

CREATE TABLE CHAT_MESSAGE_REACTIONS (
    REACTION_ID NUMBER(19) PRIMARY KEY,
    MESSAGE_ID NUMBER(19) NOT NULL,
    USER_ID NUMBER(19) NOT NULL,
    EMOJI VARCHAR2(50) NOT NULL,
    CREATED_MESSAGE_REACTION TIMESTAMP NOT NULL,
    CONSTRAINT UK_MSG_REACT UNIQUE (MESSAGE_ID, USER_ID, EMOJI),
    CONSTRAINT FK_MSG_REACT_MSG FOREIGN KEY (MESSAGE_ID) REFERENCES CHAT_MESSAGES (MESSAGE_ID) ON DELETE CASCADE,
    CONSTRAINT FK_MSG_REACT_USER FOREIGN KEY (USER_ID) REFERENCES USERS (ID)
);

CREATE TABLE MESSAGE_PROCESSES (
    PROCESS_ID NUMBER(19) PRIMARY KEY,
    CONVERSATION_ID NUMBER(19) NOT NULL,
    TITLE VARCHAR2(200) NOT NULL,
    STATUS VARCHAR2(20) NOT NULL,
    SORT_ORDER NUMBER(10) NOT NULL,
    DESIGNER_CONFIRMED NUMBER(1) DEFAULT 0 NOT NULL,
    CLIENT_CONFIRMED NUMBER(1) DEFAULT 0 NOT NULL,
    CREATED_MESSAGE_PROCESS TIMESTAMP NOT NULL,
    CONSTRAINT FK_MSG_PROC_CONV FOREIGN KEY (CONVERSATION_ID) REFERENCES MESSAGE_CONVERSATIONS (CONVERSATION_ID) ON DELETE CASCADE,
    CONSTRAINT CK_MSG_PROC_STATUS CHECK (STATUS IN ('pending', 'in-progress', 'completed')),
    CONSTRAINT CK_MSG_PROC_DES CHECK (DESIGNER_CONFIRMED IN (0, 1)),
    CONSTRAINT CK_MSG_PROC_CLI CHECK (CLIENT_CONFIRMED IN (0, 1))
);

CREATE TABLE MESSAGE_PROCESS_TASKS (
    TASK_ID NUMBER(19) PRIMARY KEY,
    PROCESS_ID NUMBER(19) NOT NULL,
    TASK_TEXT VARCHAR2(500) NOT NULL,
    COMPLETED NUMBER(1) DEFAULT 0 NOT NULL,
    SORT_ORDER NUMBER(10) NOT NULL,
    CREATED_MESSAGE_PROCESS_TASK TIMESTAMP NOT NULL,
    CONSTRAINT FK_MSG_TASK_PROC FOREIGN KEY (PROCESS_ID) REFERENCES MESSAGE_PROCESSES (PROCESS_ID) ON DELETE CASCADE,
    CONSTRAINT CK_MSG_TASK_DONE CHECK (COMPLETED IN (0, 1))
);

CREATE INDEX IDX_MESSAGE_CONV_USER_ONE ON MESSAGE_CONVERSATIONS (USER_ONE_ID);
CREATE INDEX IDX_MESSAGE_CONV_USER_TWO ON MESSAGE_CONVERSATIONS (USER_TWO_ID);
CREATE INDEX IDX_CHAT_MESSAGES_CONV_TIME ON CHAT_MESSAGES (CONVERSATION_ID, CREATED_MESSAGE);
CREATE INDEX IDX_MSG_REACT_MSG ON CHAT_MESSAGE_REACTIONS (MESSAGE_ID);
CREATE INDEX IDX_MSG_PROC_CONV_SORT ON MESSAGE_PROCESSES (CONVERSATION_ID, SORT_ORDER);
CREATE INDEX IDX_MSG_TASK_PROC_SORT ON MESSAGE_PROCESS_TASKS (PROCESS_ID, SORT_ORDER);
