CREATE SEQUENCE MESSAGE_REACTION_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE MESSAGE_REACTIONS (
    REACTION_ID NUMBER(19) PRIMARY KEY,
    MESSAGE_ID NUMBER(19) NOT NULL,
    USER_ID NUMBER(19) NOT NULL,
    EMOJI_CODE VARCHAR2(120) NOT NULL,
    CREATED_MESSAGE_REACTION TIMESTAMP NOT NULL,
    CONSTRAINT UK_MSG_REACT_MSG_USER_EMOJI UNIQUE (MESSAGE_ID, USER_ID, EMOJI_CODE),
    CONSTRAINT FK_MSG_REACT_MESSAGE FOREIGN KEY (MESSAGE_ID)
        REFERENCES CHAT_MESSAGES (MESSAGE_ID)
        ON DELETE CASCADE,
    CONSTRAINT FK_MSG_REACT_USER FOREIGN KEY (USER_ID)
        REFERENCES USERS (ID)
);

CREATE INDEX IDX_MSG_REACT_MESSAGE
ON MESSAGE_REACTIONS (MESSAGE_ID);
