DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO v_count
      FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = 'MESSAGE_CONVERSATIONS'
       AND COLUMN_NAME = 'USER_ONE_LAST_READ_MESSAGE_ID';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE MESSAGE_CONVERSATIONS ADD (USER_ONE_LAST_READ_MESSAGE_ID NUMBER(19))';
    END IF;
END;
/

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO v_count
      FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = 'MESSAGE_CONVERSATIONS'
       AND COLUMN_NAME = 'USER_TWO_LAST_READ_MESSAGE_ID';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE MESSAGE_CONVERSATIONS ADD (USER_TWO_LAST_READ_MESSAGE_ID NUMBER(19))';
    END IF;
END;
/

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO v_count
      FROM USER_SEQUENCES
     WHERE SEQUENCE_NAME = 'MESSAGE_REACTION_SEQ';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE SEQUENCE MESSAGE_REACTION_SEQ START WITH 1 INCREMENT BY 1 NOCACHE';
    END IF;
END;
/

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO v_count
      FROM USER_SEQUENCES
     WHERE SEQUENCE_NAME = 'MESSAGE_PROCESS_SEQ';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE SEQUENCE MESSAGE_PROCESS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE';
    END IF;
END;
/

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO v_count
      FROM USER_SEQUENCES
     WHERE SEQUENCE_NAME = 'MESSAGE_PROCESS_TASK_SEQ';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE SEQUENCE MESSAGE_PROCESS_TASK_SEQ START WITH 1 INCREMENT BY 1 NOCACHE';
    END IF;
END;
/

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO v_count
      FROM USER_TABLES
     WHERE TABLE_NAME = 'CHAT_MESSAGE_REACTIONS';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE q'[
            CREATE TABLE CHAT_MESSAGE_REACTIONS (
                REACTION_ID NUMBER(19) PRIMARY KEY,
                MESSAGE_ID NUMBER(19) NOT NULL,
                USER_ID NUMBER(19) NOT NULL,
                EMOJI VARCHAR2(50) NOT NULL,
                CREATED_MESSAGE_REACTION TIMESTAMP NOT NULL,
                CONSTRAINT UK_MSG_REACT UNIQUE (MESSAGE_ID, USER_ID, EMOJI),
                CONSTRAINT FK_MSG_REACT_MSG FOREIGN KEY (MESSAGE_ID) REFERENCES CHAT_MESSAGES (MESSAGE_ID) ON DELETE CASCADE,
                CONSTRAINT FK_MSG_REACT_USER FOREIGN KEY (USER_ID) REFERENCES USERS (ID)
            )
        ]';
    END IF;
END;
/

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO v_count
      FROM USER_TABLES
     WHERE TABLE_NAME = 'MESSAGE_PROCESSES';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE q'[
            CREATE TABLE MESSAGE_PROCESSES (
                PROCESS_ID NUMBER(19) PRIMARY KEY,
                CONVERSATION_ID NUMBER(19) NOT NULL,
                TITLE VARCHAR2(200) NOT NULL,
                STATUS VARCHAR2(20) NOT NULL,
                SORT_ORDER NUMBER(10) NOT NULL,
                DESIGNER_CONFIRMED NUMBER(1) DEFAULT 0 NOT NULL,
                CLIENT_CONFIRMED NUMBER(1) DEFAULT 0 NOT NULL,
                CREATED_MESSAGE_PROCESS TIMESTAMP NOT NULL,
                CONSTRAINT FK_MSG_PROC_CONV FOREIGN KEY (CONVERSATION_ID) REFERENCES MESSAGE_CONVERSATIONS (CONVERSATION_ID) ON DELETE CASCADE,
                CONSTRAINT CK_MSG_PROC_STATUS CHECK (STATUS IN ('pending', 'in-progress', 'completed')),
                CONSTRAINT CK_MSG_PROC_DES CHECK (DESIGNER_CONFIRMED IN (0, 1)),
                CONSTRAINT CK_MSG_PROC_CLI CHECK (CLIENT_CONFIRMED IN (0, 1))
            )
        ]';
    END IF;
END;
/

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO v_count
      FROM USER_TABLES
     WHERE TABLE_NAME = 'MESSAGE_PROCESS_TASKS';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE q'[
            CREATE TABLE MESSAGE_PROCESS_TASKS (
                TASK_ID NUMBER(19) PRIMARY KEY,
                PROCESS_ID NUMBER(19) NOT NULL,
                TASK_TEXT VARCHAR2(500) NOT NULL,
                COMPLETED NUMBER(1) DEFAULT 0 NOT NULL,
                SORT_ORDER NUMBER(10) NOT NULL,
                CREATED_MESSAGE_PROCESS_TASK TIMESTAMP NOT NULL,
                CONSTRAINT FK_MSG_TASK_PROC FOREIGN KEY (PROCESS_ID) REFERENCES MESSAGE_PROCESSES (PROCESS_ID) ON DELETE CASCADE,
                CONSTRAINT CK_MSG_TASK_DONE CHECK (COMPLETED IN (0, 1))
            )
        ]';
    END IF;
END;
/

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO v_count
      FROM USER_INDEXES
     WHERE INDEX_NAME = 'IDX_MSG_REACT_MSG';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX IDX_MSG_REACT_MSG ON CHAT_MESSAGE_REACTIONS (MESSAGE_ID)';
    END IF;
END;
/

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO v_count
      FROM USER_INDEXES
     WHERE INDEX_NAME = 'IDX_MSG_PROC_CONV_SORT';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX IDX_MSG_PROC_CONV_SORT ON MESSAGE_PROCESSES (CONVERSATION_ID, SORT_ORDER)';
    END IF;
END;
/

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO v_count
      FROM USER_INDEXES
     WHERE INDEX_NAME = 'IDX_MSG_TASK_PROC_SORT';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX IDX_MSG_TASK_PROC_SORT ON MESSAGE_PROCESS_TASKS (PROCESS_ID, SORT_ORDER)';
    END IF;
END;
/
