CREATE SEQUENCE MESSAGE_CONVERSATION_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE CHAT_MESSAGE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE MESSAGE_CONVERSATIONS (
    CONVERSATION_ID NUMBER(19) PRIMARY KEY,
    USER_ONE_ID NUMBER(19) NOT NULL,
    USER_TWO_ID NUMBER(19) NOT NULL,
    LAST_MESSAGE_AT TIMESTAMP,
    LAST_MESSAGE_PREVIEW VARCHAR2(500),
    CREATED_MESSAGE_CONVERSATION TIMESTAMP NOT NULL,
    CONSTRAINT UK_MESSAGE_CONVERSATION_USERS UNIQUE (USER_ONE_ID, USER_TWO_ID),
    CONSTRAINT CK_MESSAGE_CONVERSATION_USERS CHECK (USER_ONE_ID <> USER_TWO_ID),
    CONSTRAINT FK_MESSAGE_CONV_USER_ONE FOREIGN KEY (USER_ONE_ID) REFERENCES USERS (ID),
    CONSTRAINT FK_MESSAGE_CONV_USER_TWO FOREIGN KEY (USER_TWO_ID) REFERENCES USERS (ID)
);

CREATE TABLE CHAT_MESSAGES (
    MESSAGE_ID NUMBER(19) PRIMARY KEY,
    CONVERSATION_ID NUMBER(19) NOT NULL,
    SENDER_ID NUMBER(19) NOT NULL,
    CLIENT_ID VARCHAR2(100),
    MESSAGE CLOB,
    ATTACHMENTS_JSON CLOB,
    CREATED_MESSAGE TIMESTAMP NOT NULL,
    CONSTRAINT FK_CHAT_MESSAGE_CONVERSATION FOREIGN KEY (CONVERSATION_ID) REFERENCES MESSAGE_CONVERSATIONS (CONVERSATION_ID),
    CONSTRAINT FK_CHAT_MESSAGE_SENDER FOREIGN KEY (SENDER_ID) REFERENCES USERS (ID)
);

CREATE INDEX IDX_MESSAGE_CONV_USER_ONE ON MESSAGE_CONVERSATIONS (USER_ONE_ID);
CREATE INDEX IDX_MESSAGE_CONV_USER_TWO ON MESSAGE_CONVERSATIONS (USER_TWO_ID);
CREATE INDEX IDX_CHAT_MESSAGES_CONV_TIME ON CHAT_MESSAGES (CONVERSATION_ID, CREATED_MESSAGE);
