CREATE SEQUENCE MESSAGE_CONVERSATION_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE CHAT_MESSAGE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE MESSAGE_PROCESS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE MESSAGE_PROCESS_TASK_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE MESSAGE_REVIEW_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE MESSAGE_CONVERSATIONS (
    CONVERSATION_ID NUMBER(19) PRIMARY KEY,
    USER_ONE_ID NUMBER(19) NOT NULL,
    USER_TWO_ID NUMBER(19) NOT NULL,
    LAST_MESSAGE_AT TIMESTAMP,
    LAST_MESSAGE_PREVIEW VARCHAR2(500),
    CREATED_MESSAGE_CONVERSATION TIMESTAMP NOT NULL,
    CONSTRAINT UK_MESSAGE_CONVERSATION_USERS UNIQUE (USER_ONE_ID, USER_TWO_ID),
    CONSTRAINT CK_MESSAGE_CONVERSATION_USERS CHECK (USER_ONE_ID <> USER_TWO_ID),
    CONSTRAINT FK_MESSAGE_CONV_USER_ONE FOREIGN KEY (USER_ONE_ID) REFERENCES USERS (ID),
    CONSTRAINT FK_MESSAGE_CONV_USER_TWO FOREIGN KEY (USER_TWO_ID) REFERENCES USERS (ID)
);

CREATE TABLE CHAT_MESSAGES (
    MESSAGE_ID NUMBER(19) PRIMARY KEY,
    CONVERSATION_ID NUMBER(19) NOT NULL,
    SENDER_ID NUMBER(19) NOT NULL,
    CLIENT_ID VARCHAR2(100),
    MESSAGE CLOB,
    ATTACHMENTS_JSON CLOB,
    CREATED_MESSAGE TIMESTAMP NOT NULL,
    READ_AT TIMESTAMP,
    CONSTRAINT FK_CHAT_MESSAGE_CONVERSATION FOREIGN KEY (CONVERSATION_ID) REFERENCES MESSAGE_CONVERSATIONS (CONVERSATION_ID),
    CONSTRAINT FK_CHAT_MESSAGE_SENDER FOREIGN KEY (SENDER_ID) REFERENCES USERS (ID)
);

CREATE TABLE MESSAGE_PROCESSES (
    PROCESS_ID NUMBER(19) PRIMARY KEY,
    CONVERSATION_ID NUMBER(19) NOT NULL,
    TITLE VARCHAR2(200) NOT NULL,
    STATUS VARCHAR2(20) NOT NULL,
    SORT_ORDER NUMBER(10) NOT NULL,
    DESIGNER_CONFIRMED NUMBER(1) DEFAULT 0 NOT NULL,
    CLIENT_CONFIRMED NUMBER(1) DEFAULT 0 NOT NULL,
    CREATED_MESSAGE_PROCESS TIMESTAMP NOT NULL,
    CONSTRAINT FK_MESSAGE_PROCESS_CONVERSATION FOREIGN KEY (CONVERSATION_ID) REFERENCES MESSAGE_CONVERSATIONS (CONVERSATION_ID) ON DELETE CASCADE,
    CONSTRAINT CK_MESSAGE_PROCESS_STATUS CHECK (STATUS IN ('pending', 'in-progress', 'completed')),
    CONSTRAINT CK_MESSAGE_PROCESS_DESIGNER_CONF CHECK (DESIGNER_CONFIRMED IN (0, 1)),
    CONSTRAINT CK_MESSAGE_PROCESS_CLIENT_CONF CHECK (CLIENT_CONFIRMED IN (0, 1))
);

CREATE TABLE MESSAGE_PROCESS_TASKS (
    TASK_ID NUMBER(19) PRIMARY KEY,
    PROCESS_ID NUMBER(19) NOT NULL,
    TASK_TEXT VARCHAR2(500) NOT NULL,
    COMPLETED NUMBER(1) DEFAULT 0 NOT NULL,
    SORT_ORDER NUMBER(10) NOT NULL,
    CREATED_MESSAGE_PROCESS_TASK TIMESTAMP NOT NULL,
    CONSTRAINT FK_MESSAGE_PROCESS_TASK_PROCESS FOREIGN KEY (PROCESS_ID) REFERENCES MESSAGE_PROCESSES (PROCESS_ID) ON DELETE CASCADE,
    CONSTRAINT CK_MESSAGE_PROCESS_TASK_COMPLETED CHECK (COMPLETED IN (0, 1))
);

CREATE TABLE MESSAGE_REVIEWS (
    REVIEW_ID NUMBER(19) PRIMARY KEY,
    CONVERSATION_ID NUMBER(19) NOT NULL,
    REVIEWER_ID NUMBER(19) NOT NULL,
    REVIEWEE_ID NUMBER(19) NOT NULL,
    PROJECT_TITLE VARCHAR2(200) NOT NULL,
    RATING NUMBER(1) NOT NULL,
    CONTENT CLOB NOT NULL,
    WORK_CATEGORIES_JSON CLOB,
    COMPLIMENT_TAGS_JSON CLOB,
    CREATED_MESSAGE_REVIEW TIMESTAMP NOT NULL,
    CONSTRAINT UK_MESSAGE_REVIEW_CONVERSATION_REVIEWER UNIQUE (CONVERSATION_ID, REVIEWER_ID),
    CONSTRAINT FK_MESSAGE_REVIEW_CONVERSATION FOREIGN KEY (CONVERSATION_ID) REFERENCES MESSAGE_CONVERSATIONS (CONVERSATION_ID) ON DELETE CASCADE,
    CONSTRAINT FK_MESSAGE_REVIEW_REVIEWER FOREIGN KEY (REVIEWER_ID) REFERENCES USERS (ID),
    CONSTRAINT FK_MESSAGE_REVIEW_REVIEWEE FOREIGN KEY (REVIEWEE_ID) REFERENCES USERS (ID),
    CONSTRAINT CK_MESSAGE_REVIEW_RATING CHECK (RATING BETWEEN 1 AND 5),
    CONSTRAINT CK_MESSAGE_REVIEW_USERS CHECK (REVIEWER_ID <> REVIEWEE_ID)
);

CREATE INDEX IDX_MESSAGE_CONV_USER_ONE ON MESSAGE_CONVERSATIONS (USER_ONE_ID);
CREATE INDEX IDX_MESSAGE_CONV_USER_TWO ON MESSAGE_CONVERSATIONS (USER_TWO_ID);
CREATE INDEX IDX_CHAT_MESSAGES_CONV_TIME ON CHAT_MESSAGES (CONVERSATION_ID, CREATED_MESSAGE);
CREATE INDEX IDX_MESSAGE_PROCESSES_CONV_SORT ON MESSAGE_PROCESSES (CONVERSATION_ID, SORT_ORDER);
CREATE INDEX IDX_MESSAGE_PROCESS_TASKS_SORT ON MESSAGE_PROCESS_TASKS (PROCESS_ID, SORT_ORDER);
CREATE INDEX IDX_MESSAGE_REVIEWS_REVIEWEE_TIME ON MESSAGE_REVIEWS (REVIEWEE_ID, CREATED_MESSAGE_REVIEW);
