CREATE SEQUENCE MESSAGE_PROCESS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE MESSAGE_PROCESS_TASK_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE MESSAGE_PROCESSES (
    PROCESS_ID NUMBER(19) PRIMARY KEY,
    CONVERSATION_ID NUMBER(19) NOT NULL,
    TITLE VARCHAR2(200) NOT NULL,
    STATUS VARCHAR2(20) NOT NULL,
    SORT_ORDER NUMBER(10) NOT NULL,
    DESIGNER_CONFIRMED NUMBER(1) DEFAULT 0 NOT NULL,
    CLIENT_CONFIRMED NUMBER(1) DEFAULT 0 NOT NULL,
    CREATED_MESSAGE_PROCESS TIMESTAMP NOT NULL,
    CONSTRAINT FK_MSG_PROC_CONV FOREIGN KEY (CONVERSATION_ID) REFERENCES MESSAGE_CONVERSATIONS (CONVERSATION_ID) ON DELETE CASCADE,
    CONSTRAINT CK_MSG_PROC_STATUS CHECK (STATUS IN ('pending', 'in-progress', 'completed')),
    CONSTRAINT CK_MSG_PROC_DES CHECK (DESIGNER_CONFIRMED IN (0, 1)),
    CONSTRAINT CK_MSG_PROC_CLIENT CHECK (CLIENT_CONFIRMED IN (0, 1))
);

CREATE TABLE MESSAGE_PROCESS_TASKS (
    TASK_ID NUMBER(19) PRIMARY KEY,
    PROCESS_ID NUMBER(19) NOT NULL,
    TASK_TEXT VARCHAR2(500) NOT NULL,
    COMPLETED NUMBER(1) DEFAULT 0 NOT NULL,
    SORT_ORDER NUMBER(10) NOT NULL,
    CREATED_MESSAGE_PROCESS_TASK TIMESTAMP NOT NULL,
    CONSTRAINT FK_MSG_TASK_PROC FOREIGN KEY (PROCESS_ID) REFERENCES MESSAGE_PROCESSES (PROCESS_ID) ON DELETE CASCADE,
    CONSTRAINT CK_MSG_TASK_DONE CHECK (COMPLETED IN (0, 1))
);

CREATE INDEX IDX_MSG_PROC_CONV_SORT ON MESSAGE_PROCESSES (CONVERSATION_ID, SORT_ORDER);
CREATE INDEX IDX_MSG_TASK_PROC_SORT ON MESSAGE_PROCESS_TASKS (PROCESS_ID, SORT_ORDER);
